### ISSUE TITLE
Is this project alive ?

### ISSUE THREAD

**Issue by tampler** [paoloboni/binance-scala-client#1] opened 2020-03-30 06:15 UTC
Tested your ticker example, but it won't work with my API Credentials

**Comment by paoloboni** [comment] 2020-03-30 07:40
Hi, can you please provide more details on the error you are getting?

**Comment by tampler** [comment] 2020-03-30 12:49
I created a new project, included your repo and put an example code. I was expecting to see a ticker price in console. But when I start the app with my API credentials, I see a blank console and nothing happens.

I'll publish my test project to demonstrate the issue. Also, may need to do a PR to bump deps

**Comment by paoloboni** [comment] 2020-03-31 07:53
Had a quick look and the example is not working. Thanks for raising this, will have a better look later today.

**Comment by paoloboni** [comment] 2020-03-31 20:19
The issue is fixed in v0.0.7 as soon as it becomes available on Nexus.

**Closed by paoloboni** 2020-03-31 20:19 UTC

**Comment by tampler** [comment] 2020-03-31 20:44
Thanks Paolo
